# Generated by Django 4.0.6 on 2022-09-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz', '0002_payment_api_payment_type_alter_payment_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='api_payment_type',
        ),
    ]
