# Generated by Django 4.0.6 on 2022-09-11 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_rename_orderid_order_trans_id'),
        ('sslcommerz', '0003_remove_payment_api_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.order'),
        ),
    ]
