# Generated by Django 4.0.6 on 2022-08-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz', '0007_payment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='patient',
        ),
    ]
