# Generated by Django 4.0.6 on 2022-08-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz', '0008_remove_payment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='appointment',
        ),
        migrations.AddField(
            model_name='payment',
            name='appointment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
