# Generated by Django 4.0.6 on 2022-08-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz', '0010_remove_payment_appointment_id_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='patient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
