# Generated by Django 4.0.6 on 2022-08-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz', '0011_payment_patient_id_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='appointment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
