# Generated by Django 4.0.6 on 2022-08-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_appointment_payment_status_and_more'),
        ('sslcommerz', '0013_remove_payment_appointment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.appointment'),
        ),
    ]
