# Generated by Django 4.0.6 on 2022-08-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz', '0014_payment_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='consulation_fee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='report_fee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
