# Generated by Django 4.0.6 on 2022-09-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='Prescription_reqiuired',
            field=models.BooleanField(default=False, verbose_name='required'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='featured_image',
            field=models.ImageField(blank=True, default='medicines/default.png', null=True, upload_to='medicines/'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_category',
            field=models.CharField(blank=True, choices=[('fever', 'fever'), ('pain', 'pain'), ('cough', 'cough'), ('cold', 'cold'), ('flu', 'flu'), ('diabetes', 'diabetes'), ('eye', 'eye'), ('ear', 'ear'), ('allergy', 'allergy'), ('asthma', 'asthma'), ('bloodpressure', 'bloodpressure'), ('heartdisease', 'heartdisease'), ('vitamins', 'vitamins'), ('digestivehealth', 'digestivehealth'), ('skin', 'skin'), ('infection', 'infection'), ('nurological', 'nurological')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('tablets', 'tablets'), ('syrup', 'syrup'), ('capsule', 'capsule'), ('general', 'general')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
