# Generated by Django 4.0.6 on 2022-09-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='Prescription_reqiuired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
