# Generated by Django 4.0.6 on 2022-09-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_medicine_prescription_reqiuired_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='general_name',
            new_name='weight',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Prescription_reqiuired',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True),
        ),
    ]
