# Generated by Django 4.0.6 on 2022-09-11 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_cart_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderId',
            new_name='trans_ID',
        ),
    ]
