# Generated by Django 4.0.6 on 2022-09-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_rename_orderid_order_trans_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paymentId',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
