# Generated by Django 4.0.6 on 2022-09-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_rename_general_name_medicine_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='stock_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='serial_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
