# Generated by Django 4.0.6 on 2022-09-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_medicine_prescription_reqiuired'),
        ('pharmacy', '0004_medicine_stock_quantity_alter_medicine_medicine_id_and_more'),
    ]

    operations = [
    ]
