# Generated by Django 4.0.6 on 2022-09-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_merge_20220905_1840'),
        ('pharmacy', '0006_alter_medicine_prescription_reqiuired'),
    ]

    operations = [
    ]
