# Generated by Django 4.0.6 on 2022-08-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_information',
            name='featured_image',
            field=models.ImageField(blank=True, default='admin/user-default.png', null=True, upload_to='admin/'),
        ),
        migrations.AlterField(
            model_name='admin_information',
            name='role',
            field=models.CharField(blank=True, choices=[('Hospital Admin', 'Hospital Admin'), ('Laboratory', 'Laboratory Admin'), ('Pharmacy', 'Pharmacy Admin')], max_length=200, null=True),
        ),
    ]
