# Generated by Django 4.0.6 on 2022-09-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0003_test_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_information',
            name='test_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
