# Generated by Django 4.0.6 on 2022-09-18 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_user_login_status'),
        ('hospital_admin', '0004_alter_test_information_test_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_information',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.hospital_information'),
        ),
    ]
