# Generated by Django 4.0.6 on 2022-09-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0006_specialization_service_hospital_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_department',
            name='featured_image',
            field=models.ImageField(blank=True, default='departments/default.png', null=True, upload_to='departments/'),
        ),
    ]
