# Generated by Django 4.0.6 on 2022-09-04 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0007_hospital_department_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital_department',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='service',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='doctor',
        ),
    ]
