# Generated by Django 4.0.6 on 2022-08-09 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_Information',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(blank=True, max_length=200, null=True)),
                ('hospital_address', models.TextField(blank=True, null=True)),
                ('hospital_image', models.ImageField(blank=True, default='hospitals/default.png', null=True, upload_to='hospitals/')),
                ('hospital_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('hospital_phone_number', models.IntegerField(default=0)),
                ('hospital_type', models.CharField(choices=[('private', 'Private hospital'), ('public', 'Public hospital')], max_length=200)),
                ('general_bed_no', models.IntegerField(blank=True, null=True)),
                ('available_icu_no', models.IntegerField(blank=True, null=True)),
                ('regular_cabin_no', models.IntegerField(blank=True, null=True)),
                ('emergency_cabin_no', models.IntegerField(blank=True, null=True)),
                ('vip_cabin_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('patient_phone_number', models.IntegerField(blank=True, null=True)),
                ('patient_address', models.TextField(blank=True, null=True)),
                ('patient_image', models.ImageField(blank=True, default='patients/user-default.png', null=True, upload_to='patients/')),
                ('patient_blood_group', models.CharField(blank=True, max_length=200, null=True)),
                ('patient_history', models.TextField(blank=True, null=True)),
                ('patient_dob', models.DateField(blank=True, null=True)),
                ('patient_nid', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
