# Generated by Django 4.0.6 on 2022-08-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital_information',
            old_name='hospital_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='hospital_information',
            old_name='hospital_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='hospital_information',
            old_name='hospital_image',
            new_name='featured_image',
        ),
        migrations.RenameField(
            model_name='hospital_information',
            old_name='hospital_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hospital_information',
            old_name='hospital_phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_blood_group',
            new_name='blood_group',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_dob',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_image',
            new_name='featured_image',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_history',
            new_name='history',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_nid',
            new_name='nid',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_phone_number',
            new_name='phone_number',
        ),
    ]
