# Generated by Django 4.0.6 on 2022-08-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_hospital_address_hospital_information_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_information',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
