# Generated by Django 4.0.6 on 2022-07-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital_information_hospital_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_information',
            name='hospital_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
