# Generated by Django 4.0.6 on 2022-08-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_patient_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_information',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
