# Generated by Django 4.0.6 on 2022-07-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_hospital_information_hospital_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Information',
            fields=[
                ('doctor_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=200)),
                ('doctor_degree', models.TextField()),
                ('doctor_specialization', models.CharField(choices=[('Cardiologists', 'Cardiologists'), ('Neurologists', 'Neurologists'), ('Pediatricians', 'Pediatricians'), ('Physiatrists', 'Physiatrists'), ('Dermatologists', 'Dermatologists')], max_length=200)),
                ('doctor_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('doctor_email', models.CharField(max_length=200)),
                ('doctor_phone_number', models.IntegerField(default=0)),
            ],
        ),
    ]
