# Generated by Django 4.0.6 on 2022-08-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_hospital_information_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_labworker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pharmacist',
            field=models.BooleanField(default=False),
        ),
    ]
