# Generated by Django 4.0.6 on 2022-07-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_doctor_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_information',
            name='doctor_specialization',
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='doctor_consultation_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='doctor_department',
            field=models.CharField(blank=True, choices=[('Cardiologists', 'Cardiologists'), ('Neurologists', 'Neurologists'), ('Pediatricians', 'Pediatricians'), ('Physiatrists', 'Physiatrists'), ('Dermatologists', 'Dermatologists')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='doctor_report_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='doctor_visiting_hour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital_information',
            name='available_icu_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital_information',
            name='emergency_cabin_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital_information',
            name='general_bed_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital_information',
            name='regular_cabin_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital_information',
            name='vip_cabin_no',
            field=models.IntegerField(default=0),
        ),
    ]
