# Generated by Django 4.0.6 on 2022-08-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_user_is_labworker_user_is_pharmacist'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
