# Generated by Django 4.0.6 on 2022-07-26 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_doctor_information_doctor_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_information',
            name='Hospital_Information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital_information'),
        ),
        migrations.AlterField(
            model_name='hospital_information',
            name='hospital_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_information',
            name='hospital_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
