# Generated by Django 4.0.6 on 2022-07-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_doctor_information_hospital_information_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_information',
            old_name='Hospital_Information',
            new_name='Hospital_Name',
        ),
    ]
