# Generated by Django 4.0.6 on 2022-07-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_rename_hospital_information_doctor_information_hospital_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Information',
            fields=[
                ('admin_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('admin_username', models.CharField(max_length=200)),
                ('admin_phone_number', models.IntegerField(default=0)),
                ('admin_email', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_password', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_role', models.CharField(blank=True, choices=[('Hospital', 'Hospital Admin'), ('Laboratory', 'Laboratory Admin'), ('Pharmacy', 'Pharmacy Admin')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('patient_age', models.IntegerField(default=0)),
                ('patient_email', models.CharField(blank=True, max_length=200, null=True)),
                ('patient_phone_number', models.IntegerField(default=0)),
                ('patient_address', models.TextField(blank=True, null=True)),
                ('patient_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('patient_blood_group', models.CharField(max_length=200)),
                ('patient_history', models.TextField(blank=True, null=True)),
                ('patient_password', models.CharField(blank=True, max_length=200, null=True)),
                ('patient_dob', models.DateField(blank=True, null=True)),
                ('patient_nid', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Details',
            fields=[
                ('payment_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_email', models.CharField(max_length=200)),
                ('patient_phone_number', models.IntegerField(default=0)),
                ('paid_amount', models.IntegerField(default=0)),
                ('transaction_id', models.TextField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('fee_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test_information',
            fields=[
                ('test_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=200)),
                ('test_fee', models.IntegerField(default=0)),
                ('test_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='doctor_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='doctor_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_information',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_information',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Report_Information',
            fields=[
                ('report_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('report_time', models.TimeField(blank=True, null=True)),
                ('delivery_date', models.TimeField(blank=True, null=True)),
                ('report_description', models.TextField(blank=True, null=True)),
                ('report_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('total_report_fee', models.IntegerField(default=0)),
                ('Hospital_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital_information')),
                ('patient_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
                ('report_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor_information')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('appointment_type', models.CharField(max_length=200)),
                ('serial_number', models.IntegerField(default=0)),
                ('appointment_fee_status', models.CharField(max_length=200)),
                ('Hospital_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital_information')),
                ('Patient_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
                ('doctor_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor_information')),
            ],
        ),
    ]
