# Generated by Django 4.0.6 on 2022-07-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_admin_information_patient_payment_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Hospital_name',
            new_name='Hospital_Name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor_name',
            new_name='appointment_doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Patient_name',
            new_name='appointment_patient',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_fee_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
