# Generated by Django 4.0.6 on 2022-07-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_rename_hospital_name_appointment_hospital_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Hospital_Name',
        ),
    ]
