# Generated by Django 4.0.6 on 2022-07-28 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_remove_appointment_hospital_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_patient',
            new_name='Patient_name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_doctor',
            new_name='doctor_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Hospital_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital_information'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('Report', 'Report'), ('Checkup', 'Checkup')], max_length=200),
        ),
    ]
