# Generated by Django 4.0.6 on 2022-07-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_rename_appointment_patient_appointment_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_information',
            name='report_type',
            field=models.CharField(blank=True, choices=[('Urgent', 'Urgent'), ('Normal', 'Normal')], max_length=200, null=True),
        ),
    ]
