# Generated by Django 4.0.6 on 2022-08-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_report_information_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_information',
            name='hospital_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_information',
            name='hospital_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
