# Generated by Django 4.0.6 on 2022-08-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_alter_hospital_information_hospital_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_information',
            name='hospital_image',
            field=models.ImageField(blank=True, default='Normal/hospitals/default.png', null=True, upload_to='Normal/hospitals/'),
        ),
    ]
