# Generated by Django 4.0.6 on 2022-08-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_alter_hospital_information_hospital_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_information',
            name='hospital_image',
            field=models.ImageField(blank=True, default='hospitals/default.png', null=True, upload_to='hospitals/'),
        ),
    ]
