# Generated by Django 4.0.6 on 2022-08-08 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0015_alter_hospital_information_hospital_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_information',
            name='doctor_password',
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='doctor_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctor_information',
            name='doctor_consultation_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_information',
            name='doctor_degree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_information',
            name='doctor_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_information',
            name='doctor_image',
            field=models.ImageField(blank=True, default='doctors/user-default.png', null=True, upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='doctor_information',
            name='doctor_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_information',
            name='doctor_report_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_information',
            name='available_icu_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_information',
            name='emergency_cabin_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_information',
            name='general_bed_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_information',
            name='regular_cabin_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital_information',
            name='vip_cabin_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
