# Generated by Django 4.0.6 on 2022-08-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_remove_admin_information_admin_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_information',
            old_name='doctor_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='admin_information',
            name='hospital_admin',
        ),
    ]
