# Generated by Django 4.0.6 on 2022-08-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_rename_doctor_user_doctor_information_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
