# Generated by Django 4.0.6 on 2022-08-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_rename_patient_email_patient_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_information',
            old_name='doctor_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='doctor_information',
            old_name='doctor_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
