# Generated by Django 4.0.6 on 2022-09-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('appointment_type', models.CharField(choices=[('report', 'report'), ('checkup', 'checkup')], max_length=200)),
                ('appointment_status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_status', models.CharField(blank=True, default='pending', max_length=200, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Information',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('department', models.CharField(blank=True, choices=[('Cardiologists', 'Cardiologists'), ('Neurologists', 'Neurologists'), ('Pediatricians', 'Pediatricians'), ('Physiatrists', 'Physiatrists'), ('Dermatologists', 'Dermatologists')], max_length=200, null=True)),
                ('featured_image', models.ImageField(blank=True, default='doctors/user-default.png', null=True, upload_to='doctors/')),
                ('certificate_image', models.ImageField(blank=True, default='doctors_certificate/default.png', null=True, upload_to='doctors_certificate/')),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('visiting_hour', models.CharField(blank=True, max_length=200, null=True)),
                ('consultation_fee', models.IntegerField(blank=True, null=True)),
                ('report_fee', models.IntegerField(blank=True, null=True)),
                ('dob', models.CharField(blank=True, max_length=200, null=True)),
                ('institute', models.CharField(blank=True, max_length=200, null=True)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('completion_year', models.CharField(blank=True, max_length=200, null=True)),
                ('work_place', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('start_year', models.CharField(blank=True, max_length=200, null=True)),
                ('end_year', models.CharField(blank=True, max_length=200, null=True)),
                ('register_status', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('institute', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_completion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_place_name', models.CharField(blank=True, max_length=200, null=True)),
                ('from_year', models.CharField(blank=True, max_length=200, null=True)),
                ('to_year', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.CharField(blank=True, max_length=200, null=True)),
                ('days', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.CharField(blank=True, max_length=200, null=True)),
                ('medicine_description', models.TextField(blank=True, null=True)),
                ('test_name', models.CharField(blank=True, max_length=200, null=True)),
                ('test_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('specimen_id', models.CharField(blank=True, max_length=200, null=True)),
                ('specimen_type', models.CharField(blank=True, max_length=200, null=True)),
                ('collection_date', models.CharField(blank=True, max_length=200, null=True)),
                ('receiving_date', models.CharField(blank=True, max_length=200, null=True)),
                ('test_name', models.CharField(blank=True, max_length=200, null=True)),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('referred_value', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_date', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor_information')),
            ],
        ),
    ]
