# Generated by Django 4.0.6 on 2022-09-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_information',
            name='service',
        ),
    ]
