# Generated by Django 4.0.6 on 2022-09-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_remove_test_delivery_date_report_other_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_information',
            name='nid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_information',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
