# Generated by Django 4.0.6 on 2022-08-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_report_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_information',
            name='educational_institute',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='end_year',
            field=models.CharField(blank=True, default='Present', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='start_year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='work_experience_years',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='work_place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='year_of_completion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
