# Generated by Django 4.0.6 on 2022-08-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_doctor_information_educational_institute_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_information',
            old_name='end_year',
            new_name='edu_end_year_1',
        ),
        migrations.RenameField(
            model_name='doctor_information',
            old_name='educational_institute',
            new_name='edu_start_year_1',
        ),
        migrations.RenameField(
            model_name='doctor_information',
            old_name='start_year',
            new_name='educational_institute_1',
        ),
        migrations.RemoveField(
            model_name='doctor_information',
            name='year_of_completion',
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='end_year_1',
            field=models.CharField(blank=True, default='Present', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='start_year_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
