# Generated by Django 4.0.6 on 2022-08-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_rename_end_year_doctor_information_edu_end_year_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_information',
            old_name='edu_start_year_1',
            new_name='completion_year',
        ),
        migrations.RenameField(
            model_name='doctor_information',
            old_name='educational_institute_1',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='doctor_information',
            old_name='start_year_1',
            new_name='end_year',
        ),
        migrations.RenameField(
            model_name='doctor_information',
            old_name='work_experience_years',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='doctor_information',
            name='edu_end_year_1',
        ),
        migrations.RemoveField(
            model_name='doctor_information',
            name='end_year_1',
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='institute',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='start_year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
