# Generated by Django 4.0.6 on 2022-09-09 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_prescription_extra_information'),
        ('doctor', '0011_alter_prescription_patient_alter_report_doctor'),
    ]

    operations = [
    ]
