# Generated by Django 4.0.6 on 2022-08-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_rename_edu_start_year_1_doctor_information_completion_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_information',
            name='dob',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
