# Generated by Django 4.0.6 on 2022-09-04 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0008_remove_hospital_department_doctor_and_more'),
        ('doctor', '0014_doctor_information_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_information',
            name='department_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.hospital_department'),
        ),
    ]
