# Generated by Django 4.0.6 on 2022-09-04 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0008_remove_hospital_department_doctor_and_more'),
        ('doctor', '0015_doctor_information_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_information',
            name='service_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.service'),
        ),
        migrations.AddField(
            model_name='doctor_information',
            name='specialization_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.specialization'),
        ),
    ]
