# Generated by Django 4.1.1 on 2022-09-13 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_test_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_cart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.perscription_test'),
        ),
    ]
