# Generated by Django 4.0.6 on 2022-09-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_test_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perscription_test',
            name='prescription',
        ),
    ]
