# Generated by Django 4.0.6 on 2022-09-12 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_remove_perscription_test_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Info',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(blank=True, max_length=200, null=True)),
                ('test_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='perscription_test',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.prescription'),
        ),
    ]
