# Generated by Django 4.0.6 on 2022-09-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_test_info_perscription_test_prescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_Info',
        ),
    ]
