# Generated by Django 4.0.6 on 2022-09-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_delete_test_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='perscription_medicine',
            new_name='Prescription_medicine',
        ),
        migrations.RenameModel(
            old_name='perscription_test',
            new_name='Prescription_test',
        ),
    ]
