# Generated by Django 4.0.6 on 2022-09-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_doctor_information_certicate_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_information',
            old_name='certicate_image',
            new_name='certificate_image',
        ),
    ]
