# Generated by Django 4.1.1 on 2022-09-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_alter_test_cart_item'),
        ('doctor', '0019_delete_test_info'),
    ]

    operations = [
    ]
