# Generated by Django 4.1.1 on 2022-09-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_merge_0017_alter_test_cart_item_0019_delete_test_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_cart',
            name='test_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
