# Generated by Django 4.0.6 on 2022-09-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_doctor_information_login_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_information',
            name='login_status',
        ),
    ]
