# Generated by Django 4.1.1 on 2022-09-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_test_cart_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_cart',
            name='test_name',
        ),
        migrations.AddField(
            model_name='test_cart',
            name='name',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
