# Generated by Django 4.0.6 on 2022-09-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_doctor_information_login_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='create_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
