# Generated by Django 4.1.1 on 2022-09-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_rename_perscription_medicine_prescription_medicine_and_more'),
        ('doctor', '0022_remove_test_cart_test_name_test_cart_name'),
    ]

    operations = [
    ]
