# Generated by Django 4.1.1 on 2022-09-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0022_prescription_create_date'),
        ('doctor', '0022_remove_doctor_information_login_status'),
        ('doctor', '0023_merge_20220914_1911'),
    ]

    operations = [
    ]
