# Generated by Django 4.0.6 on 2022-09-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0025_prescription_test_info_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='test_info_id',
        ),
        migrations.AddField(
            model_name='prescription_test',
            name='test_info_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
