# Generated by Django 4.0.6 on 2022-09-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0026_remove_prescription_test_info_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_test',
            name='test_info_id',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
