# Generated by Django 4.0.6 on 2022-09-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0026_remove_prescription_test_info_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_cart',
            name='quantity',
        ),
    ]
