# Generated by Django 4.0.6 on 2022-09-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0028_prescription_test_test_info_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription_test',
            name='test_info_pay_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
