# Generated by Django 4.0.6 on 2022-09-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0027_alter_prescription_test_test_info_id'),
        ('doctor', '0029_prescription_test_test_info_pay_status'),
    ]

    operations = [
    ]
