# Generated by Django 4.0.6 on 2022-09-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0029_prescription_test_test_info_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_test',
            name='test_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
