# Generated by Django 4.0.6 on 2022-09-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0030_alter_prescription_test_test_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_test',
            name='test_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
