# Generated by Django 4.0.6 on 2022-09-15 14:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz', '0005_payment_test_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0031_alter_prescription_test_test_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test_Cart',
            new_name='testCart',
        ),
        migrations.RenameModel(
            old_name='test_Order',
            new_name='testOrder',
        ),
    ]
