# Generated by Django 4.1.1 on 2022-09-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0027_doctor_review'),
        ('doctor', '0031_alter_prescription_test_test_description'),
    ]

    operations = [
    ]
