# Generated by Django 4.0.6 on 2022-09-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0027_doctor_review'),
        ('doctor', '0032_rename_test_cart_testcart_and_more'),
    ]

    operations = [
    ]
