# Generated by Django 4.0.6 on 2022-09-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0027_doctor_review'),
        ('doctor', '0032_merge_20220915_2039'),
    ]

    operations = [
    ]
