# Generated by Django 4.0.6 on 2022-09-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0033_merge_0027_doctor_review_0032_merge_20220915_2039'),
        ('doctor', '0033_merge_20220915_2105'),
    ]

    operations = [
    ]
