# Generated by Django 4.0.6 on 2022-09-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0032_rename_test_cart_testcart_and_more'),
        ('doctor', '0033_merge_0027_doctor_review_0032_merge_20220915_2039'),
    ]

    operations = [
    ]
