# Generated by Django 4.0.6 on 2022-09-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0034_merge_20220915_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_test',
            name='test_info_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
