# Generated by Django 4.1.1 on 2022-09-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0032_merge_20220915_2055'),
        ('doctor', '0035_alter_prescription_test_test_info_id'),
    ]

    operations = [
    ]
