# Generated by Django 4.0.6 on 2022-09-16 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0034_merge_20220915_2122'),
        ('doctor', '0035_alter_prescription_test_test_info_id'),
    ]

    operations = [
    ]
