# Generated by Django 4.1.1 on 2022-09-16 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0034_merge_20220915_2122'),
        ('doctor', '0036_merge_20220915_2130'),
    ]

    operations = [
    ]
