# Generated by Django 4.1.1 on 2022-09-17 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0036_merge_20220916_1041'),
        ('doctor', '0037_merge_20220916_1045'),
    ]

    operations = [
    ]
