# Generated by Django 4.0.6 on 2022-09-17 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0038_merge_20220916_1159'),
        ('doctor', '0038_merge_20220917_0933'),
    ]

    operations = [
    ]
