# Generated by Django 4.0.6 on 2022-09-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0036_merge_20220916_0205'),
        ('doctor', '0039_merge_20220917_1247'),
    ]

    operations = [
    ]
