# Generated by Django 4.1.1 on 2022-09-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0040_merge_20220917_1746'),
        ('doctor', '0040_merge_20220917_1856'),
    ]

    operations = [
    ]
