# Generated by Django 4.0.6 on 2022-09-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0040_merge_20220917_1855'),
        ('doctor', '0041_merge_20220917_1905'),
    ]

    operations = [
    ]
