# Generated by Django 4.0.6 on 2022-09-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0043_merge_20220918_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
